<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Comment;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Method returns comments list from new to old.
     *
     * @return array
     */
    public function getAllComments($projectId)
    {
        $qb = $this->getEntityManager()
            ->createQuery('SELECT c FROM AppBundle\Entity\Comment c WHERE c.projectId = :projectId ORDER BY c.createdAt DESC')
            ->setParameter('projectId', (int)$projectId);

        return $qb->getResult();
    }
}
