<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Comment;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Method returns comments list from new to old.
     *
     * @return array
     */
    public function getAllComments()
    {
        $qb = $this->getEntityManager()
            ->createQuery('SELECT c FROM AppBundle\Entity\Comment c WHERE c.projectId = 874 ORDER BY c.createdAt DESC');

        return $qb->getResult();
    }
}
